### ISSUE TITLE
long to String cast problem

### ISSUE THREAD

**Issue by sekiguchi-nagisa** [konoha-project/libzen#25]
at commit cd9f9c680bf8ef2cd876b197ee3215939175279c

$ cat cast.zen
 function f() {
    return "hello" + 1;
}

f();
skgchxngsxyz-opensuse@linux-nt0w:~/workspace/libzen> java -jar libzen.jar -l jvm ./cast.zen 
setname=Assert__1qqe
setname=Assert__2qqe
setname=Size__1qqy
setname=f__0qqw
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
        at Ff__0qqw.f(./cast.zen:2)
        at Ff__0qqw.Invoke(./cast.zen)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at zen.codegen.jvm.JavaEngine.InvokeMethod(JavaEngine.java:191)
        at zen.codegen.jvm.JavaEngine.VisitFuncCallNode(JavaEngine.java:361)
        at zen.ast.ZFuncCallNode.Accept(ZFuncCallNode.java:59)
        at zen.parser.ZScriptEngine.Eval(ZScriptEngine.java:125)
        at zen.codegen.jvm.JavaEngine.VisitCastNode(JavaEngine.java:377)
        at zen.ast.ZCastNode.Accept(ZCastNode.java:44)
        at zen.parser.ZScriptEngine.Eval(ZScriptEngine.java:125)
        at zen.parser.ZScriptEngine.Exec(ZScriptEngine.java:351)
        at zen.parser.ZScriptEngine.Eval(ZScriptEngine.java:364)
        at zen.parser.ZScriptEngine.Eval(ZScriptEngine.java:379)
        at zen.parser.ZScriptEngine.Load(ZScriptEngine.java:388)
        at zen.main.ZenMain.ExecCommand(ZenMain.java:195)
        at zen.main.ZenMain.main(ZenMain.java:268)
(./cast.zen:5) [error] invocation error: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
        f();
         ^
EXIT  zen.main.ZenMain.main(ZenMain.java:268)abort loading: ./cast.zen

**Comment by imasahiro** [comment]
It seems jvm codegenerator's bug.  I wrote a reduced test case.

```
$ cat cast.zen
function f() {
    return (String) 1;
}
f();
```
