### ISSUE TITLE
Infinite loop and out of memory error

### ISSUE THREAD

**Issue by syohex** [konoha-project/libzen#28]
```
% java -jar libzen.jar
FIXME: Overide GetEngine in each generator!!
LibZen0.1 (Reference Implementation of D-Script) on Java JVM-1.7.0_51
Copyright (c) 2013-2014, Konoha project authors
Accept: zen-0.1 zen-trycatch-0.1 zen-class-0.1
Produce: zen0.1
>>> function f(a int)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2367)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
    at java.lang.StringBuilder.append(StringBuilder.java:132)
    at zen.parser.ZSource.MakeBody(ZSource.java:146)
    at zen.parser.ZLogger.Report(ZLogger.java:60)
    at zen.parser.ZLogger.ReportError(ZLogger.java:83)
    at zen.parser.ZSourceEngine.VisitErrorNode(ZSourceEngine.java:403)
    at zen.ast.ZErrorNode.Accept(ZErrorNode.java:42)
    at zen.parser.ZSourceEngine.Eval(ZSourceEngine.java:107)
    at zen.parser.ZSourceEngine.Exec(ZSourceEngine.java:116)
    at zen.parser.ZSourceEngine.Eval(ZSourceEngine.java:129)
    at zen.parser.ZSourceEngine.Eval(ZSourceEngine.java:144)
    at zen.main.ZenMain.ExecCommand(ZenMain.java:153)
    at zen.main.ZenMain.main(ZenMain.java:208)
java -jar libzen.jar  153.09s user 1.39s system 96% cpu 2:40.11 total
```

I understand this input is wrong(missing `:` after argument variable)
however `libzen` should return error message immediately.

**Comment by kkuramitsu** [comment]
Thank you.
I understood what happened!!
I can handle it if I have time.
Kimio

On Thu, Feb 20, 2014 at 3:08 PM, Syohei YOSHIDA notifications@github.comwrote:

> % java -jar libzen.jar
> FIXME: Overide GetEngine in each generator!!
> LibZen0.1 (Reference Implementation of D-Script) on Java JVM-1.7.0_51
> Copyright (c) 2013-2014, Konoha project authors
> Accept: zen-0.1 zen-trycatch-0.1 zen-class-0.1
> Produce: zen0.1
> 
> > > > function f(a int)
> > > > Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
> > > >     at java.util.Arrays.copyOf(Arrays.java:2367)
> > > >     at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
> > > >     at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
> > > >     at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
> > > >     at java.lang.StringBuilder.append(StringBuilder.java:132)
> > > >     at zen.parser.ZSource.MakeBody(ZSource.java:146)
> > > >     at zen.parser.ZLogger.Report(ZLogger.java:60)
> > > >     at zen.parser.ZLogger.ReportError(ZLogger.java:83)
> > > >     at zen.parser.ZSourceEngine.VisitErrorNode(ZSourceEngine.java:403)
> > > >     at zen.ast.ZErrorNode.Accept(ZErrorNode.java:42)
> > > >     at zen.parser.ZSourceEngine.Eval(ZSourceEngine.java:107)
> > > >     at zen.parser.ZSourceEngine.Exec(ZSourceEngine.java:116)
> > > >     at zen.parser.ZSourceEngine.Eval(ZSourceEngine.java:129)
> > > >     at zen.parser.ZSourceEngine.Eval(ZSourceEngine.java:144)
> > > >     at zen.main.ZenMain.ExecCommand(ZenMain.java:153)
> > > >     at zen.main.ZenMain.main(ZenMain.java:208)
> > > > java -jar libzen.jar  153.09s user 1.39s system 96% cpu 2:40.11 total
> 
> I understand this input is wrong(missing : after argument variable)
> however libzen should return error message immediately.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/konoha-project/libzen/issues/28
> .

## 

Kimio Kuramitsu, Ph.D. Associate Professor
kimio@ynu.ac.jp    http://www.ubicg.ynu.ac.jp/
Konoha Project Leader. http://konoha.sourceforge.jp/
TEL +81-45-339-4139(4128) FAX: +81-45-338-1157

**Comment by syohex** [comment]
I confirmed this issue is fixed.
