### ISSUE TITLE
parenthesised expression raises NullPointerException

### ISSUE THREAD

**Issue by syohex** [konoha-project/libzen#38]
```
% java -jar libzen.jar
LibZen0.1 (Reference Implementation of D-Script) on Java JVM-1.7.0_51
Copyright (c) 2013-2014, Konoha project authors
Accept: zen-0.1 zen-trycatch-0.1 
Produce: 0.1
>>> (1)
java.lang.NullPointerException
    at zen.parser.ZToken.IsNameSymbol(ZToken.java:111)
    at zen.grammar.ExpressionPatternFunction._DispatchPattern(ExpressionPatternFunction.java:46)
    at zen.grammar.RightExpressionPatternFunction.Invoke(RightExpressionPatternFunction.java:10)
    at zen.util.LibZen._ApplyMatchFunc(LibZen.java:499)
    at zen.parser.ZTokenContext.ApplyMatchPattern(ZTokenContext.java:251)
    at zen.parser.ZTokenContext.ParsePatternAfter(ZTokenContext.java:277)
    at zen.parser.ZTokenContext.ParsePattern(ZTokenContext.java:282)
    at zen.parser.ZTokenContext.MatchPattern(ZTokenContext.java:288)
    at zen.parser.ZTokenContext.MatchPattern(ZTokenContext.java:313)
    at zen.grammar.CastPatternFunction.Invoke(CastPatternFunction.java:17)
    at zen.util.LibZen._ApplyMatchFunc(LibZen.java:499)
    at zen.parser.ZTokenContext.ApplyMatchPattern(ZTokenContext.java:251)
    at zen.grammar.ExpressionPatternFunction._DispatchPattern(ExpressionPatternFunction.java:43)
    at zen.grammar.StatementPatternFunction.Invoke(StatementPatternFunction.java:14)
    at zen.util.LibZen._ApplyMatchFunc(LibZen.java:499)
    at zen.parser.ZTokenContext.ApplyMatchPattern(ZTokenContext.java:251)
    at zen.parser.ZTokenContext.ParsePatternAfter(ZTokenContext.java:277)
    at zen.parser.ZTokenContext.ParsePattern(ZTokenContext.java:282)
    at zen.parser.ZGenerator.LoadScript(ZGenerator.java:370)
    at zen.main.ZenMain.ExecCommand(ZenMain.java:150)
    at zen.main.ZenMain.main(ZenMain.java:194)
    at <TopLevel>.TopLevelEval(stdin:1)
>>> 
```

**Comment by kkuramitsu** [comment]
Thank you for informing us

Sent from my iPhone
  Kimio

**Comment by syohex** [comment]
I confirmed this issues is fixed.
