### ISSUE TITLE
NullPointerException is thrown when unary operator is inputed

### ISSUE THREAD

**Issue by syohex** [konoha-project/libzen#6]
I got following log.

```
% java -jar libzen.jar
LibZen0.1 (Reference Implementation of D-Script) on Java JVM-1.7.0_25
Copyright (c) 2013-2014, Konoha project authors
Accept: zen0.1
Produce: zen0.1
>>> -1
java.lang.NullPointerException
    at zen.lang.ZenType.Accept(ZenType.java:91)
    at zen.lang.ZenTypeChecker.TypeCheckImpl(ZenTypeChecker.java:314)
    at zen.lang.ZenTypeChecker.TypeCheck(ZenTypeChecker.java:298)
    at zen.parser.ZenNameSpace.TypeCheck(ZenNameSpace.java:566)
    at zen.parser.ZenNameSpace.Eval(ZenNameSpace.java:577)
    at zen.main.ZenMain.ExecCommand(ZenMain.java:213)
    at zen.main.ZenMain.main(ZenMain.java:266)
    at <TopLevel>.TopLevelEval(stdin:1)
```

**Comment by syohex** [comment]
This issue may be fixed at 9127a634a16dcd8aa9228d06190db31448d7a9c6
