### ISSUE TITLE
NullPointerException is thrown when return statement is inputed

### ISSUE THREAD

**Issue by syohex** [konoha-project/libzen#9]
I got following log.

```
% java -jar libzen.jar
LibZen0.1 (Reference Implementation of D-Script) on Java JVM-1.7.0_25
Copyright (c) 2013-2014, Konoha project authors
Accept: zen0.1
Produce: zen0.1
>>> return 0;   
java.lang.NullPointerException
    at zen.lang.ZenTypeChecker.TypeCheckImpl(ZenTypeChecker.java:317)
    at zen.lang.ZenTypeChecker.TypeCheck(ZenTypeChecker.java:298)
    at zen.lang.ZenDynamicTypeChecker.VisitReturnNode(ZenDynamicTypeChecker.java:351)
    at zen.ast.ZenReturnNode.Accept(ZenReturnNode.java:40)
    at zen.lang.ZenTypeChecker.TypeCheck(ZenTypeChecker.java:295)
    at zen.parser.ZenNameSpace.TypeCheck(ZenNameSpace.java:566)
    at zen.parser.ZenNameSpace.Eval(ZenNameSpace.java:577)
    at zen.main.ZenMain.ExecCommand(ZenMain.java:213)
    at zen.main.ZenMain.main(ZenMain.java:266)
    at <TopLevel>.TopLevelEval(stdin:1)
```

**Comment by syohex** [comment]
This problem had been fixed.
I close
